-- Shared setup/teardown helpers for the `*.headless.lua` integration scripts
-- under this directory (see save_on_exit.headless.lua and
-- hydrate_universe.headless.lua). This file is deliberately named so neither
-- the busted `*_spec.lua` glob nor the CI `*.headless.lua` glob collect it:
-- it is a plain support module, not a runnable test itself.

local persistance = require("multiverse.repositories.persistance")
local json = require("multiverse.repositories.json")
local addNewUniverseUsecase = require("multiverse.usecases.addNewUniverseUsecase")
local neotree_plugin = require("plugins.neotree_plugin")
local on_exit = require("multiverse.autocmd.on_exit")
local state_store = require("multiverse.store.state_store")

local M = {}

function M.read_file(path)
	local file = io.open(path, "r")
	assert(file ~= nil, "expected file to exist at " .. path)
	local contents = file:read("*a")
	file:close()
	return contents
end

--- Redirects persisted state to throwaway temp directories and stubs out the
--- Neotree plugin hooks so beforeDehydrate/afterHydrate don't attempt to run
--- `:Neotree ...` ex commands, which don't exist in a `-u NONE` headless
--- session. neotree_integration.hydrate() already guards itself with
--- `vim.fn.exists(":Neotree")`, but neotree_plugin's own
--- beforeDehydrate/afterHydrate hooks call `vim.cmd("Neotree ...")`
--- unconditionally.
---@return table ctx with persistance_dir, universe_directory, and restore()
function M.setup()
	local persistance_dir = vim.fn.tempname()
	vim.fn.mkdir(persistance_dir, "p")

	local original_getDir = persistance.getDir
	persistance.getDir = function()
		return persistance_dir
	end

	local original_neotree_beforeDehydrate = neotree_plugin.context.beforeDehydrate
	local original_neotree_afterHydrate = neotree_plugin.context.afterHydrate
	neotree_plugin.context.beforeDehydrate = function() end
	neotree_plugin.context.afterHydrate = function() end

	-- A real directory on disk, standing in for the universe's working
	-- directory.
	local universe_directory = vim.fn.tempname()
	vim.fn.mkdir(universe_directory, "p")
	-- addNewUniverseUsecase.run() normalizes whatever directory it's given
	-- (vim.fs.normalize(...):gsub("/$", "")) before persisting it, so
	-- normalize here too to keep comparisons against persisted paths exact.
	local expanded = vim.fs.normalize(universe_directory)
	universe_directory = (expanded:gsub("/$", ""))

	local ctx = {
		persistance_dir = persistance_dir,
		universe_directory = universe_directory,
	}

	function ctx.restore()
		persistance.getDir = original_getDir
		neotree_plugin.context.beforeDehydrate = original_neotree_beforeDehydrate
		neotree_plugin.context.afterHydrate = original_neotree_afterHydrate

		vim.fn.delete(persistance_dir, "rf")
		vim.fn.delete(universe_directory, "rf")
	end

	return ctx
end

--- Creates a real universe via addNewUniverseUsecase.run() (rather than
--- hand-rolling multiverse/universe records), opens a real tracked buffer
--- inside it, and fires the real QuitPre autocmd so
--- multiverse_manager.save() dehydrates and persists real buffer state to
--- universe-<uuid>.json.
---
--- Note: addNewUniverseUsecase.run() reaches
--- multiverse_manager.load_universe() -> hydration_manager.hydrate(), which
--- is the only thing in this pipeline that actually `:cd`s into the
--- universe's working directory (multiverse_manager.save() itself only reads
--- the cwd, it never changes it).
---@param ctx table returned by M.setup()
---@param name string
---@return string tracked_file_path
---@return string universe_uuid
function M.create_and_save_universe(ctx, name)
	addNewUniverseUsecase.run(name, ctx.universe_directory)

	-- Find the uuid the usecase generated by reading back the real
	-- multiverse.json it wrote.
	local multiverse_json = json.decode(M.read_file(ctx.persistance_dir .. "/multiverse.json"))
	assert(#multiverse_json.universes == 1,
		"expected exactly one registered universe, found " .. #multiverse_json.universes)
	local universe_summary = multiverse_json.universes[1]
	assert(universe_summary.uuid ~= nil, "expected the registered universe to have a uuid")

	-- Open a real buffer with known content -- this is the state we expect the
	-- exit-save pipeline to capture.
	local tracked_file_path = ctx.universe_directory .. "/tracked_file.lua"
	local tracked_fh = io.open(tracked_file_path, "w")
	assert(tracked_fh ~= nil, "expected to be able to open " .. tracked_file_path .. " for writing")
	tracked_fh:write("-- tracked by " .. name .. "\n")
	tracked_fh:close()

	vim.api.nvim_command("edit " .. vim.fn.fnameescape(tracked_file_path))

	-- Register the real QuitPre -> multiverse_manager.save() autocmd.
	on_exit.register()

	-- state_store must be IDLE for multiverse_manager.save() to actually
	-- persist rather than bailing out with "Cannot save universe while in
	-- state: ...".
	assert(state_store.get_current_state() == state_store.STATES.IDLE,
		"expected state_store to be IDLE before firing QuitPre, but was: " .. state_store.get_current_state())

	-- Fire the real autocmd, exercising the full
	-- QuitPre -> multiverse_manager.save() -> dehydration_manager.dehydrate() ->
	-- universe_repository.save_universe() pipeline -- nothing here is called
	-- directly.
	vim.api.nvim_exec_autocmds("QuitPre", {})

	return tracked_file_path, universe_summary.uuid
end

return M
