name: Busted

on:
  push:
  pull_request:

jobs:
  specs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.1"

      - uses: leafo/gh-actions-luarocks@v4

      - name: Install busted
        run: luarocks install busted

      - name: Run busted specs
        run: busted
